### PR TITLE
Fix '/' in room-id or mxid breaking navigation

### LINKED ISSUE #451: Can't open rooms with slashes in the ID
**To Reproduce**
1. Join a room whose room ID contains a slash (`/`), e.g. [#test:maunium.net](https://matrix.to/#/#test:maunium.net) (room ID `!test/v7 🐈️:maunium.net`)
2. Try to open the room in Hydrogen
3. Hydrogen says "You are not currently in !test. Want to join it?"

**Expected behavior**
The room is opened and the user can send messages

**Screenshots**
image

**Smartphone (please complete the following information):**
 - Device: Nokia 8.3 5G
 - OS: Android 11
 - Browser: Firefox 91.0.0-beta.6
 - Version: 0.2.5

### PR DESCRIPTION
**Pull request by MidhunSureshR**
Fixes #451

### CODE REVIEW

File: src/domain/navigation/index.ts [hunk 1]
```diff
@@ -176,7 +176,7 @@ export function parseUrlPath(urlPath: string, currentNavPath: Path<SegmentType>,
         } else if (type === "details" || type === "members") {
             pushRightPanelSegment(segments, type);
         } else if (type === "member") {
-            const userId = iterator.next().value;
+            const userId = decodeURIComponent(iterator.next().value);
```
Comment (bwindels) [inline src/domain/navigation/index.ts]: `userId` can be `undefined` here, which `decodeURIComponent` helpfully converts into the truthy `"undefined"` value, so should convert after this check.

File: src/domain/navigation/index.ts [hunk 2]
```diff
@@ -147,7 +147,7 @@ export function parseUrlPath(urlPath: string, currentNavPath: Path<SegmentType>,
                 segments.push(new Segment("empty-grid-tile", selectedIndex));
             }
         } else if (type === "open-room") {
-            const roomId = iterator.next().value;
+            const roomId = decodeURIComponent(iterator.next().value);
```
Comment (bwindels) [inline src/domain/navigation/index.ts]: same here as for `userId`

File: src/domain/navigation/index.ts [hunk 3]
```diff
@@ -217,15 +222,28 @@ export function stringifyPath(path: Path<SegmentType>): string {
...
     return urlPath;
 }
 
+function encodeSegmentValue(value: SegmentType[keyof SegmentType]) {
+    if (typeof value === "boolean") {
+        // Nothing to encode for boolean
+        return value;
+    }
+    else if (Array.isArray(value)) {
+        return value.map(v => encodeURIComponent(v));
```
Comment (bwindels) [inline src/domain/navigation/index.ts]: could do the `.join(",")` straight here, as it's part of the encoding it to a string process...
