### PR TITLE
Fix progressbar not working on attachment uploads

### LINKED ISSUE #570: Progress bar for image uploads don't work on Chrome
But they do work on Firefox.

### LINKED ISSUE #581: File uploads (as opposed to images) don't show upload progress
They just report "Uploading: 0%" and go directly to "Sent"

### PR DESCRIPTION
**Pull request by MidhunSureshR**
Fixes #570 and #581

### CODE REVIEW

File: src/platform/web/docroot/sw.js [hunk 1]
```diff
@@ -69,7 +69,9 @@ async function purgeOldCaches() {
 }
 
 self.addEventListener('fetch', (event) => {
-    event.respondWith(handleRequest(event.request));
+    if (event.request.method === "GET") {
```
Comment (bwindels) [inline src/platform/web/docroot/sw.js:77]: can we add a comment here that we intercepting uploads here would break progress events?

**Review by bwindels — APPROVED** [review]
